services:
  - type: web
    name: MSU-Southwest-Lansing-Project
    env: python
    plan: free
    region: ohio
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips='*' --timeout 120"
    autoDeploy: true
    healthCheckPath: "/healthz"
    envVars:
      - key: PYTHONVERSION
        value: 3.14.3